# enable/disable serverside ping holograms for players without ping mod [requires ProtocolLib]
enableServerPings: true
# show username in serverside ping hologram
serverPingUsername: true
# lifetime of serverside ping hologram in seconds
serverPingDuration: 4

# players who have disabled pings
pingBlacklist:
  - 00000000-0000-0000-0000-000000000000