# serverside ping holograms for players without ping mod [requires ProtocolLib]
serverPings:
  enabled: true
  # show username in ping hologram
  showPingUsername: true
  # lifetime of ping hologram in seconds
  pingDuration: 4
  # how often distance in the ping hologram gets updated in ticks [20 ticks per second]
  # set to 0 to disable showing distance in the hologram
  pingRefreshRate: 4

# players who have disabled pings
pingBlacklist:
  - 00000000-0000-0000-0000-000000000000